version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: todo_list_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_db:
    image: redis:latest
    container_name: cache_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    environment:
      REDIS_USERNAME: cache_db
      REDIS_PASSWORD: password123



volumes:
  postgres_data:
  redis_data:
