spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_list_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false

  data:
    redis:
      host: localhost
      port: 6379
      username: admin
      password: admin123

application:
  security:
    jwt:
      secret-key: bXlwZXJmZWN0c2VjcmV0a2V5dG8gdXNlIHdpdGggSlBXVA==
      expiration: 60000000
data:
    redis:
       port: 6379
       host: localhost
       password: admin123